Fiap/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {

            ViewData["NomeDoAluno"] = "Thiago";
            ViewBag.NovoNomeDoAluno = "Thiagao";

            ViewBag.ConteudoSinistro = "<script>alert('oi')</script>";


            var pessoa = new Pessoa() { Nome = "Thiago" };
            var homeViewModel = new HomeViewModel() { totalDeNoticias = 123 };
            return View(homeViewModel);
        }


        [HttpGet]
        public IActionResult Redirect(string url)
        {

            if (Url.IsLocalUrl(url))
                return LocalRedirect(url);
            else
                return LocalRedirect("/");

        }

        [HttpGet]
        public IActionResult Teste()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Sobre()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index([FromBody]Pessoa pessoa, [FromHeader]string AppVersion)
        {
            return View();
        }

        public IActionResult Edit(int nomeDoCliente)
        {
            return View();
        }

        public IActionResult Salvar(DadosX pessoa)
        {
            return View();
        }
    }

    public class Pessoa
    {
        public string Nome { get; set; }
    }

    public class DadosX
    {
        public string AppVersion { get; set; }

    }

}

Fiap/ViewComponents/NoticiasViewComponent.cs
using Fiap.Core.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fiap.ViewComponents
{
    public class NoticiasViewComponent :ViewComponent
    {
        private INoticiaService _noticiaService;

        public NoticiasViewComponent(INoticiaService noticiaService)
        {
            _noticiaService = noticiaService;
        }
        public async Task<IViewComponentResult> InvokeAsync(int quantidade, bool noticiasurgentes)
        {
            string view = "noticias";
            if (noticiasurgentes)
            {
                view = "noticiasUrgentes";
            }

            return View(view, _noticiaService.Load());
        }

        
    }
}

Fiap/Views/Home/Index.cshtml
@model HomeViewModel

<p>Teste</p>
<div class="row">
    <div id="carroseul" class="col">
        <div class="jcarousel-wrapper">
            <div class="jcarousel">
                <ul>
                    <li>
                        <img class="carroseulimage" src="~/images/imagem-1.jpg" />
                    </li>
                    <li>
                        <img class="carroseulimage" src="~/images/imagem-2.jpg" />
                    </li>
                    <li>
                        <img class="carroseulimage" src="~/images/imagem-3.jpg" />
                    </li>
                    <li>
                        <img class="carroseulimage" src="~/images/imagem-4.jpg" />
                    </li>
                </ul>
            </div>
            <div>
                <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
                <a href="#" class="jcarousel-control-next">&rsaquo;</a>
            </div>
            <div>	    </div>

        </div>
    </div>
</div>


<div class="row">
    <div id="menu">
        <ul>
            <li>
                @*<img class="icon" src="~/images/brasil.png" />*@
                <div class="icon bandeiras brasil"></div>

                Brasil
            </li>
            <li>
                @*<img class="icon" src="~/images/alemanha.png" />*@
                <div class="icon bandeiras alemanha"></div>
                Alemanha
            </li>
            <li>
                @*<img class="icon" src="~/images/grecia.png" />*@
                <div class="icon bandeiras grecia"></div>
                Grecia
            </li>
            <li>
                @*<img class="icon" src="~/images/eua.png"*@ 
                <div class="icon bandeiras eua"></div>
                EUA
            </li>
            <li>
                @*<img class="icon" src="~/images/canada.png" />*@
                <div class="icon bandeiras canada"></div>
                Canada
            </li>
            <li>
                @*<img class="icon" src="~/images/argentina.png" />*@
                <div class="icon bandeiras argentina"></div>
                Argentina
            </li>
            <li>
                <div class="icon bandeiras japao"></div>
                
                @*<img class="icon" src="~/images/japao.png" />*@
                Japão
            </li>
            <li>
                @*<img class="icon" src="~/images/italia.png" />*@
                <div class="icon bandeiras italia"></div>

                Italia
            </li>
            <li>
                @*<img class="icon" src="~/images/espanha.png" />*@
                <div class="icon bandeiras espanha"></div>
                Espanha
            </li>
            <li>
                <div class="icon bandeiras portugal"></div>
                @*<img class="icon" src="~/images/portugal.png" />*@
                Portugal
            </li>
        </ul>
    </div>
</div>



<div class="row">
    <div class=" col">
        <vc:noticias quantidade="3" noticiasurgentes="true"></vc:noticias>
    </div>
</div>

Fiap/Views/Home/Sobre.cshtml
@{
    Layout = null;

}
<h1>Sobre nosso site</h1>